USE master
GO

DROP DATABASE IF EXISTS SAL_SCOUTS
GO

CREATE DATABASE SAL_SCOUTS
ON PRIMARY(
	-- Creamos archivo del sistema primario "SAL_SCOUTS_main.mdf"
	NAME = SAL_SCOUTS_main,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SALSCOUTS\MSSQL\DATA\SAL_SCOUTS_main.mdf',
	SIZE = 1000MB,
	MAXSIZE = 2000MB,
	FILEGROWTH = 250MB
),

-- Creamos dos filegroups "SAL_SCOUTS_FG01.ndf" y "_FG02.ndf"
FILEGROUP SAL_SCOUTS_FG (
	NAME = SAL_SCOUTS_FG01,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SALSCOUTS\MSSQL\DATA\SAL_SCOUTS_FG01.ndf',
	SIZE = 500MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 125MB
),
(
	NAME = SAL_SCOUTS_FG02,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SALSCOUTS\MSSQL\DATA\SAL_SCOUTS_FG02.ndf',
	SIZE = 500MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 125MB
)

-- Creamos dos archivos de registro "SAL_SCOUTS_log.ldf" y "_log2.ldf"
LOG ON (
	NAME = SAL_SCOUTS_log,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SALSCOUTS\MSSQL\DATA\SAL_SCOUTS_log.ldf',
	SIZE = 250MB,
	MAXSIZE = 500MB,
	FILEGROWTH = 75MB
),
(
	NAME = SAL_SCOUTS_log2,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SALSCOUTS\MSSQL\DATA\SAL_SCOUTS_log2.ldf',
	SIZE = 250MB,
	MAXSIZE = 500MB,
	FILEGROWTH = 75MB
);
GO

USE SAL_SCOUTS
GO

ALTER DATABASE SAL_SCOUTS
	ADD FILEGROUP [SAL_SCOUTS_FILESTREAM_Main]
	CONTAINS FILESTREAM
GO

ALTER DATABASE SAL_SCOUTS
	ADD FILE (
		NAME = 'SAL_SCOUTS_FILESTREAM_Main',
		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SALSCOUTS\MSSQL\DATA\filestream'
	)
	TO FILEGROUP [SAL_SCOUTS_FILESTREAM_Main]
GO

DROP TABLE IF EXISTS SAL_CASTORES
GO

CREATE TABLE SAL_CASTORES 
    (
     ID_grupo_scout INTEGER NOT NULL , 
     simbolo_castores VARBINARY (max) FILESTREAM NOT NULL,
	 ID_img UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE ,
     num_castores INTEGER , 
     num_grupos_castores INTEGER 
    )
GO

ALTER TABLE SAL_CASTORES ADD CONSTRAINT SAL_CASTORES_PK PRIMARY KEY CLUSTERED (ID_grupo_scout)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_COORDINADOR
GO

CREATE TABLE SAL_COORDINADOR 
    (
     ID_coordinador INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_COORDINADOR ADD CONSTRAINT SAL_COORDINADOR_PK PRIMARY KEY CLUSTERED (ID_coordinador)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_DONACION
GO

CREATE TABLE SAL_DONACION 
    (
     ID_donacion INTEGER NOT NULL , 
     fecha_donacion DATE NOT NULL , 
     nombre_donante NVARCHAR (250) , 
     importe MONEY NOT NULL , 
     SAL_EVENTOS_ID_evento INTEGER NOT NULL , 
     SAL_TESORERO_ID_personal INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_DONACION ADD CONSTRAINT SAL_DONACION_PK PRIMARY KEY CLUSTERED (ID_donacion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_ENTIDAD
GO

CREATE TABLE SAL_ENTIDAD 
    (
     ID_entidad INTEGER NOT NULL , 
     CIF VARCHAR (8) NOT NULL , 
     nombre_entidad NVARCHAR (255) NOT NULL , 
     direccion NVARCHAR (250) NOT NULL , 
     pais NVARCHAR (250) NOT NULL , 
     telefono INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_ENTIDAD ADD CONSTRAINT SAL_ENTIDAD_PK PRIMARY KEY CLUSTERED (ID_entidad)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE SAL_ENTIDAD ADD CONSTRAINT SAL_CIF_ENTIDAD_UK UNIQUE NONCLUSTERED (CIF)
GO

DROP TABLE IF EXISTS SAL_ENTIDAD_MATERIAL
GO

CREATE TABLE SAL_ENTIDAD_MATERIAL 
    (
     SAL_ENTIDAD_ID_entidad INTEGER NOT NULL , 
     SAL_MATERIAL_ID_material INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_ENTIDAD_MATERIAL ADD CONSTRAINT SAL_ENTIDAD_MATERIAL_PK PRIMARY KEY CLUSTERED (SAL_ENTIDAD_ID_entidad, SAL_MATERIAL_ID_material)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_EVENTOS
GO

CREATE TABLE SAL_EVENTOS 
    (
     ID_evento INTEGER NOT NULL , 
     nombre_evento NVARCHAR (255) NOT NULL , 
     fecha_hora_inicio DATETIME NOT NULL , 
     fecha_hora_final DATETIME NOT NULL , 
     lugar NVARCHAR (250) NOT NULL , 
     objetivo NVARCHAR (max) , 
     descripcion NVARCHAR (max) , 
     SAL_GRUPO_SCOUT_ID_grupo_scout INTEGER NOT NULL , 
     SAL_ENTIDAD_ID_entidad INTEGER NOT NULL , 
     SAL_COORDINADOR_ID_personal INTEGER NOT NULL , 
     SAL_RESP_COM_RRSS_ID_personal INTEGER NOT NULL , 
     SAL_SCOUTER_ID_personal INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_EVENTOS ADD CONSTRAINT SAL_EVENTOS_PK PRIMARY KEY CLUSTERED (ID_evento)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_EXPLORADORES
GO

CREATE TABLE SAL_EXPLORADORES 
    (
     ID_grupo_scout INTEGER NOT NULL , 
     simbolo_exploradores VARBINARY (max) FILESTREAM NOT NULL,
	 ID_img UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE , 
     num_exploradores INTEGER , 
     num_grupos_exploradores INTEGER 
    )
GO

ALTER TABLE SAL_EXPLORADORES ADD CONSTRAINT SAL_EXPLORADORES_PK PRIMARY KEY CLUSTERED (ID_grupo_scout)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_FACTURA_MATERIAL
GO

CREATE TABLE SAL_FACTURA_MATERIAL 
    (
     ID_factura INTEGER NOT NULL , 
     SAL_ENTIDAD_ID_entidad INTEGER NOT NULL , 
     fecha_compra DATE NOT NULL , 
     num_orden INTEGER NOT NULL , 
     fecha_pedido DATE NOT NULL , 
     producto NVARCHAR (100) NOT NULL , 
     cod_producto INTEGER NOT NULL , 
     num_lote VARCHAR (20) , 
     cantidad INTEGER NOT NULL , 
     precio MONEY NOT NULL , 
     subtotal MONEY NOT NULL , 
     total MONEY NOT NULL 
    )
GO

ALTER TABLE SAL_FACTURA_MATERIAL ADD CONSTRAINT SAL_FACTURA_MATERIAL_PK PRIMARY KEY CLUSTERED (ID_factura)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_GRUPO_SCOUT
GO

CREATE TABLE SAL_GRUPO_SCOUT 
    (
     ID_grupo_scout INTEGER NOT NULL,
	 SAL_SCOUTER_ID_scouter INTEGER NOT NULL
    )
GO

ALTER TABLE SAL_GRUPO_SCOUT ADD CONSTRAINT SAL_GRUPO_SCOUT_PK PRIMARY KEY CLUSTERED (ID_grupo_scout)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_INSIGNIA
GO

CREATE TABLE SAL_INSIGNIA 
    (
     ID_insignia INTEGER NOT NULL , 
     nombre_insignia NVARCHAR (50) NOT NULL , 
     simbolo_insignia VARBINARY (max) FILESTREAM NOT NULL,
	 ID_img UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE ,
     veces_entregada INTEGER , 
     descripcion NVARCHAR (max) 
    )
GO

ALTER TABLE SAL_INSIGNIA ADD CONSTRAINT SAL_INSIGNIA_PK PRIMARY KEY CLUSTERED (ID_insignia)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_INVENTARIO
GO

CREATE TABLE SAL_INVENTARIO 
    (
     ID_inventario INTEGER NOT NULL , 
     nombre_inventario NVARCHAR (50) NOT NULL , 
     descripcion NVARCHAR (max) , 
     SAL_RESP_MATERIALES_ID_personal INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_INVENTARIO ADD CONSTRAINT SAL_INVENTARIO_PK PRIMARY KEY CLUSTERED (ID_inventario)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_LOBATOS
GO

CREATE TABLE SAL_LOBATOS 
    (
     ID_grupo_scout INTEGER NOT NULL , 
     simbolo_lobatos VARBINARY (max) FILESTREAM NOT NULL,
	 ID_img UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE , 
     num_lobatos INTEGER , 
     num_grupos_lobatos INTEGER 
    )
GO

ALTER TABLE SAL_LOBATOS ADD CONSTRAINT SAL_LOBATOS_PK PRIMARY KEY CLUSTERED (ID_grupo_scout)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_MATERIAL
GO

CREATE TABLE SAL_MATERIAL 
    (
     ID_material INTEGER NOT NULL , 
     nombre_material NVARCHAR (100) NOT NULL , 
     cantidad_material INTEGER NOT NULL , 
     descripcion NVARCHAR (max) , 
     SAL_INVENTARIO_ID_inventario INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_MATERIAL ADD CONSTRAINT SAL_MATERIAL_PK PRIMARY KEY CLUSTERED (ID_material)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_PERSONAL
GO

CREATE TABLE SAL_PERSONAL 
    (
     ID_personal INTEGER NOT NULL , 
     nombre NVARCHAR (255) NOT NULL , 
     apellido1 NVARCHAR (255) NOT NULL , 
     apellido2 NVARCHAR (255) NOT NULL , 
     DNI VARCHAR (9) NOT NULL , 
     fecha_nacimiento DATE NOT NULL , 
     telefono INTEGER NOT NULL , 
     direccion NVARCHAR (250) NOT NULL , 
     foto_perfil VARBINARY (max) FILESTREAM NOT NULL,
	 ID_img UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE ,
     num_insignias INTEGER , 
     anos_exp_scout INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_PERSONAL ADD CONSTRAINT SAL_PERSONAL_PK PRIMARY KEY CLUSTERED (ID_personal)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE SAL_PERSONAL ADD CONSTRAINT SAL_DNI_PERSONAL_UK UNIQUE NONCLUSTERED (DNI)
GO

DROP TABLE IF EXISTS SAL_PERSONAL_INSIGNIA
GO

CREATE TABLE SAL_PERSONAL_INSIGNIA 
    (
     SAL_PERSONAL_ID_personal INTEGER NOT NULL , 
     SAL_INSIGNIA_ID_insignia INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_PERSONAL_INSIGNIA ADD CONSTRAINT SAL_PERSONAL_INSIGNIA_PK PRIMARY KEY CLUSTERED (SAL_PERSONAL_ID_personal, SAL_INSIGNIA_ID_insignia)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_PIONEROS
GO

CREATE TABLE SAL_PIONEROS 
    (
     ID_grupo_scout INTEGER NOT NULL , 
     simbolo_pioneros VARBINARY (max) FILESTREAM NOT NULL,
	 ID_img UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE ,
     num_pioneros INTEGER , 
     num_grupos_pioneros INTEGER 
    )
GO

ALTER TABLE SAL_PIONEROS ADD CONSTRAINT SAL_PIONEROS_PK PRIMARY KEY CLUSTERED (ID_grupo_scout)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_PRESIDENTE
GO

CREATE TABLE SAL_PRESIDENTE 
    (
     ID_personal INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_PRESIDENTE ADD CONSTRAINT SAL_PRESIDENTE_PK PRIMARY KEY CLUSTERED (ID_personal)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_PROYECTO
GO

CREATE TABLE SAL_PROYECTO 
    (
     ID_proyecto INTEGER NOT NULL , 
     nombre_proyecto NVARCHAR (255) NOT NULL , 
     fecha_inicio DATE NOT NULL , 
     fecha_fin DATE NOT NULL , 
     num_participantes INTEGER NOT NULL , 
     horas_servicio INTEGER NOT NULL , 
     descripcion NVARCHAR (max) , 
     SAL_INVENTARIO_ID_inventario INTEGER NOT NULL , 
     SAL_SCOUTER_ID_personal INTEGER NOT NULL , 
     SAL_COORDINADOR_ID_personal INTEGER NOT NULL , 
     SAL_RESP_COM_RRSS_ID_personal INTEGER NOT NULL , 
     SAL_GRUPO_SCOUT_ID_grupo_scout INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_PROYECTO ADD CONSTRAINT SAL_PROYECTO_PK PRIMARY KEY CLUSTERED (ID_proyecto)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_RESP_COM_RRSS
GO

CREATE TABLE SAL_RESP_COM_RRSS 
    (
     ID_resp_com_rrss INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_RESP_COM_RRSS ADD CONSTRAINT SAL_RESP_COM_RRSS_PK PRIMARY KEY CLUSTERED (ID_resp_com_rrss)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_RESP_MATERIALES
GO

CREATE TABLE SAL_RESP_MATERIALES 
    (
     ID_resp_materiales INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_RESP_MATERIALES ADD CONSTRAINT SAL_RESP_MATERIALES_PK PRIMARY KEY CLUSTERED (ID_resp_materiales)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_RESPONSABLE
GO

CREATE TABLE SAL_RESPONSABLE 
    (
     ID_responsable INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_RESPONSABLE ADD CONSTRAINT SAL_RESPONSABLE_PK PRIMARY KEY CLUSTERED (ID_responsable)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_REUNION
GO

CREATE TABLE SAL_REUNION 
    (
     ID_reunion INTEGER NOT NULL , 
     fecha_hora_inicio DATETIME NOT NULL , 
     fecha_hora_final DATETIME NOT NULL , 
     nom_reunion VARCHAR (50) NOT NULL , 
     descripcion NVARCHAR (max) , 
     lugar NVARCHAR (250) NOT NULL , 
     SAL_SCOUTER_ID_personal INTEGER NOT NULL , 
     SAL_GRUPO_SCOUT_ID_grupo_scout INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_REUNION ADD CONSTRAINT SAL_REUNION_PK PRIMARY KEY CLUSTERED (ID_reunion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_RUTAS
GO

CREATE TABLE SAL_RUTAS 
    (
     ID_grupo_scout INTEGER NOT NULL , 
     simbolo_rutas VARBINARY (max) FILESTREAM NOT NULL,
	 ID_img UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE ,
     num_rutas INTEGER , 
     num_grupos_rutas INTEGER 
    )
GO

ALTER TABLE SAL_RUTAS ADD CONSTRAINT SAL_RUTAS_PK PRIMARY KEY CLUSTERED (ID_grupo_scout)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_SCOUT
GO

CREATE TABLE SAL_SCOUT 
    (
     ID_scout INTEGER NOT NULL , 
     nombre NVARCHAR (255) NOT NULL , 
     apellido1 NVARCHAR (255) NOT NULL , 
     apellido2 NVARCHAR (255) NOT NULL , 
     DNI VARCHAR (9) NOT NULL , 
     fecha_nacimiento DATE NOT NULL , 
     direccion NVARCHAR (250) NOT NULL , 
     telefono INTEGER , 
     edad INTEGER NOT NULL , 
     foto_perfil VARBINARY (max) FILESTREAM NOT NULL,
	 ID_img UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE ,
     num_insignias INTEGER , 
     SAL_SCOUT_PADRES_ID_scout_padres INTEGER NOT NULL , 
     SAL_GRUPO_SCOUT_ID_grupo_scout INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_SCOUT ADD CONSTRAINT SAL_SCOUT_PK PRIMARY KEY CLUSTERED (ID_scout)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE SAL_SCOUT ADD CONSTRAINT SAL_DNI_SCOUT_UK UNIQUE NONCLUSTERED (DNI)
GO

DROP TABLE IF EXISTS SAL_SCOUT_INSIGNIA
GO

CREATE TABLE SAL_SCOUT_INSIGNIA 
    (
     SAL_INSIGNIA_ID_insignia INTEGER NOT NULL , 
     SAL_SCOUT_ID_scout INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_SCOUT_INSIGNIA ADD CONSTRAINT SAL_SCOUT_INSIGNIA_PK PRIMARY KEY CLUSTERED (SAL_INSIGNIA_ID_insignia, SAL_SCOUT_ID_scout)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_SCOUT_PADRES
GO

CREATE TABLE SAL_SCOUT_PADRES 
    (
     ID_scout_padres INTEGER NOT NULL , 
     nombre_padre NVARCHAR (255) , 
     apellidos_padre NVARCHAR (255) , 
     DNI_padre VARCHAR (9) , 
     tlf_padre INTEGER , 
     nombre_madre NVARCHAR (255) , 
     apellidos_madre NVARCHAR (255) , 
     DNI_madre VARCHAR (9) , 
     tlf_madre INTEGER , 
     nombre_tutor_legal NVARCHAR (255) , 
     apellidos_tuto_legal NVARCHAR (255) , 
     DNI_tutor_legal VARCHAR (9) , 
     tlf_tutor_legal INTEGER 
    )
GO

ALTER TABLE SAL_SCOUT_PADRES ADD CONSTRAINT SAL_SCOUT_PADRES_PK PRIMARY KEY CLUSTERED (ID_scout_padres)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_SCOUTER
GO

CREATE TABLE SAL_SCOUTER 
    (
     ID_scouter INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_SCOUTER ADD CONSTRAINT SAL_SCOUTER_PK PRIMARY KEY CLUSTERED (ID_scouter)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS SAL_TESORERO

CREATE TABLE SAL_TESORERO 
    (
     ID_tesorero INTEGER NOT NULL 
    )
GO

ALTER TABLE SAL_TESORERO ADD CONSTRAINT SAL_TESORERO_PK PRIMARY KEY CLUSTERED (ID_tesorero)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE SAL_CASTORES 
    ADD CONSTRAINT SAL_CASTORES_SAL_GRUPO_SCOUT_FK FOREIGN KEY 
    ( 
     ID_grupo_scout
    ) 
    REFERENCES SAL_GRUPO_SCOUT 
    ( 
     ID_grupo_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_COORDINADOR 
    ADD CONSTRAINT SAL_COORDINADOR_SAL_PERSONAL_FK FOREIGN KEY 
    ( 
     ID_coordinador
    ) 
    REFERENCES SAL_PERSONAL 
    ( 
     ID_personal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_DONACION 
    ADD CONSTRAINT SAL_DONACION_SAL_EVENTOS_FK FOREIGN KEY 
    ( 
     SAL_EVENTOS_ID_evento
    ) 
    REFERENCES SAL_EVENTOS 
    ( 
     ID_evento 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_DONACION 
    ADD CONSTRAINT SAL_DONACION_SAL_TESORERO_FK FOREIGN KEY 
    ( 
     SAL_TESORERO_ID_personal
    ) 
    REFERENCES SAL_TESORERO 
    ( 
     ID_tesorero 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_ENTIDAD_MATERIAL 
    ADD CONSTRAINT SAL_ENTIDAD_MATERIAL_SAL_ENTIDAD_FK FOREIGN KEY 
    ( 
     SAL_ENTIDAD_ID_entidad
    ) 
    REFERENCES SAL_ENTIDAD 
    ( 
     ID_entidad 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_ENTIDAD_MATERIAL 
    ADD CONSTRAINT SAL_ENTIDAD_MATERIAL_SAL_MATERIAL_FK FOREIGN KEY 
    ( 
     SAL_MATERIAL_ID_material
    ) 
    REFERENCES SAL_MATERIAL 
    ( 
     ID_material 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_EVENTOS 
    ADD CONSTRAINT SAL_EVENTOS_SAL_COORDINADOR_FK FOREIGN KEY 
    ( 
     SAL_COORDINADOR_ID_personal
    ) 
    REFERENCES SAL_COORDINADOR 
    ( 
     ID_coordinador 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_EVENTOS 
    ADD CONSTRAINT SAL_EVENTOS_SAL_ENTIDAD_FK FOREIGN KEY 
    ( 
     SAL_ENTIDAD_ID_entidad
    ) 
    REFERENCES SAL_ENTIDAD 
    ( 
     ID_entidad 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_EVENTOS 
    ADD CONSTRAINT SAL_EVENTOS_SAL_GRUPO_SCOUT_FK FOREIGN KEY 
    ( 
     SAL_GRUPO_SCOUT_ID_grupo_scout
    ) 
    REFERENCES SAL_GRUPO_SCOUT 
    ( 
     ID_grupo_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_EVENTOS 
    ADD CONSTRAINT SAL_EVENTOS_SAL_RESP_COM_RRSS_FK FOREIGN KEY 
    ( 
     SAL_RESP_COM_RRSS_ID_personal
    ) 
    REFERENCES SAL_RESP_COM_RRSS 
    ( 
     ID_resp_com_rrss 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_EVENTOS 
    ADD CONSTRAINT SAL_EVENTOS_SAL_SCOUTER_FK FOREIGN KEY 
    ( 
     SAL_SCOUTER_ID_personal
    ) 
    REFERENCES SAL_SCOUTER 
    ( 
     ID_scouter 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_EXPLORADORES 
    ADD CONSTRAINT SAL_EXPLORADORES_SAL_GRUPO_SCOUT_FK FOREIGN KEY 
    ( 
     ID_grupo_scout
    ) 
    REFERENCES SAL_GRUPO_SCOUT 
    ( 
     ID_grupo_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_FACTURA_MATERIAL 
    ADD CONSTRAINT SAL_FACTURA_MATERIAL_SAL_ENTIDAD_FK FOREIGN KEY 
    ( 
     SAL_ENTIDAD_ID_entidad
    ) 
    REFERENCES SAL_ENTIDAD 
    ( 
     ID_entidad 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_GRUPO_SCOUT
    ADD CONSTRAINT SAL_GRUPO_SCOUT_SAL_SCOUTER_FK FOREIGN KEY 
    ( 
     SAL_SCOUTER_ID_scouter
    ) 
    REFERENCES SAL_SCOUTER 
    ( 
     ID_scouter
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_INVENTARIO 
    ADD CONSTRAINT SAL_INVENTARIO_SAL_RESP_MATERIALES_FK FOREIGN KEY 
    ( 
     SAL_RESP_MATERIALES_ID_personal
    ) 
    REFERENCES SAL_RESP_MATERIALES 
    ( 
     ID_resp_materiales 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_LOBATOS 
    ADD CONSTRAINT SAL_LOBATOS_SAL_GRUPO_SCOUT_FK FOREIGN KEY 
    ( 
     ID_grupo_scout
    ) 
    REFERENCES SAL_GRUPO_SCOUT 
    ( 
     ID_grupo_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_MATERIAL 
    ADD CONSTRAINT SAL_MATERIAL_SAL_INVENTARIO_FK FOREIGN KEY 
    ( 
     SAL_INVENTARIO_ID_inventario
    ) 
    REFERENCES SAL_INVENTARIO 
    ( 
     ID_inventario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_PERSONAL_INSIGNIA 
    ADD CONSTRAINT SAL_PERSONAL_INSIGNIA_SAL_INSIGNIA_FK FOREIGN KEY 
    ( 
     SAL_INSIGNIA_ID_insignia
    ) 
    REFERENCES SAL_INSIGNIA 
    ( 
     ID_insignia 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_PERSONAL_INSIGNIA 
    ADD CONSTRAINT SAL_PERSONAL_INSIGNIA_SAL_PERSONAL_FK FOREIGN KEY 
    ( 
     SAL_PERSONAL_ID_personal
    ) 
    REFERENCES SAL_PERSONAL 
    ( 
     ID_personal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_PIONEROS 
    ADD CONSTRAINT SAL_PIONEROS_SAL_GRUPO_SCOUT_FK FOREIGN KEY 
    ( 
     ID_grupo_scout
    ) 
    REFERENCES SAL_GRUPO_SCOUT 
    ( 
     ID_grupo_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_PRESIDENTE 
    ADD CONSTRAINT SAL_PRESIDENTE_SAL_PERSONAL_FK FOREIGN KEY 
    ( 
     ID_personal
    ) 
    REFERENCES SAL_PERSONAL 
    ( 
     ID_personal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_PROYECTO 
    ADD CONSTRAINT SAL_PROYECTO_SAL_COORDINADOR_FK FOREIGN KEY 
    ( 
     SAL_COORDINADOR_ID_personal
    ) 
    REFERENCES SAL_COORDINADOR 
    ( 
     ID_coordinador 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_PROYECTO 
    ADD CONSTRAINT SAL_PROYECTO_SAL_GRUPO_SCOUT_FK FOREIGN KEY 
    ( 
     SAL_GRUPO_SCOUT_ID_grupo_scout
    ) 
    REFERENCES SAL_GRUPO_SCOUT 
    ( 
     ID_grupo_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_PROYECTO 
    ADD CONSTRAINT SAL_PROYECTO_SAL_INVENTARIO_FK FOREIGN KEY 
    ( 
     SAL_INVENTARIO_ID_inventario
    ) 
    REFERENCES SAL_INVENTARIO 
    ( 
     ID_inventario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_PROYECTO 
    ADD CONSTRAINT SAL_PROYECTO_SAL_RESP_COM_RRSS_FK FOREIGN KEY 
    ( 
     SAL_RESP_COM_RRSS_ID_personal
    ) 
    REFERENCES SAL_RESP_COM_RRSS 
    ( 
     ID_resp_com_rrss 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_PROYECTO 
    ADD CONSTRAINT SAL_PROYECTO_SAL_SCOUTER_FK FOREIGN KEY 
    ( 
     SAL_SCOUTER_ID_personal
    ) 
    REFERENCES SAL_SCOUTER 
    ( 
     ID_scouter 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_RESP_COM_RRSS 
    ADD CONSTRAINT SAL_RESP_COM_RRSS_SAL_RESPONSABLE_FK FOREIGN KEY 
    ( 
     ID_resp_com_rrss
    ) 
    REFERENCES SAL_RESPONSABLE 
    ( 
     ID_responsable 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_RESP_MATERIALES 
    ADD CONSTRAINT SAL_RESP_MATERIALES_SAL_RESPONSABLE_FK FOREIGN KEY 
    ( 
     ID_resp_materiales
    ) 
    REFERENCES SAL_RESPONSABLE 
    ( 
     ID_responsable 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_RESPONSABLE 
    ADD CONSTRAINT SAL_RESPONSABLE_SAL_PERSONAL_FK FOREIGN KEY 
    ( 
     ID_responsable
    ) 
    REFERENCES SAL_PERSONAL 
    ( 
     ID_personal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_REUNION 
    ADD CONSTRAINT SAL_REUNION_SAL_GRUPO_SCOUT_FK FOREIGN KEY 
    ( 
     SAL_GRUPO_SCOUT_ID_grupo_scout
    ) 
    REFERENCES SAL_GRUPO_SCOUT 
    ( 
     ID_grupo_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_REUNION 
    ADD CONSTRAINT SAL_REUNION_SAL_SCOUTER_FK FOREIGN KEY 
    ( 
     SAL_SCOUTER_ID_personal
    ) 
    REFERENCES SAL_SCOUTER 
    ( 
     ID_scouter 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_RUTAS 
    ADD CONSTRAINT SAL_RUTAS_SAL_GRUPO_SCOUT_FK FOREIGN KEY 
    ( 
     ID_grupo_scout
    ) 
    REFERENCES SAL_GRUPO_SCOUT 
    ( 
     ID_grupo_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_SCOUT_INSIGNIA 
    ADD CONSTRAINT SAL_SCOUT_INSIGNIA_SAL_INSIGNIA_FK FOREIGN KEY 
    ( 
     SAL_INSIGNIA_ID_insignia
    ) 
    REFERENCES SAL_INSIGNIA 
    ( 
     ID_insignia 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_SCOUT_INSIGNIA 
    ADD CONSTRAINT SAL_SCOUT_INSIGNIA_SAL_SCOUT_FK FOREIGN KEY 
    ( 
     SAL_SCOUT_ID_scout
    ) 
    REFERENCES SAL_SCOUT 
    ( 
     ID_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_SCOUT 
    ADD CONSTRAINT SAL_SCOUT_SAL_GRUPO_SCOUT_FK FOREIGN KEY 
    ( 
     SAL_GRUPO_SCOUT_ID_grupo_scout
    ) 
    REFERENCES SAL_GRUPO_SCOUT 
    ( 
     ID_grupo_scout 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_SCOUT 
    ADD CONSTRAINT SAL_SCOUT_SAL_SCOUT_PADRES_FK FOREIGN KEY 
    ( 
     SAL_SCOUT_PADRES_ID_scout_padres
    ) 
    REFERENCES SAL_SCOUT_PADRES 
    ( 
     ID_scout_padres 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_SCOUTER 
    ADD CONSTRAINT SAL_SCOUTER_SAL_PERSONAL_FK FOREIGN KEY 
    ( 
     ID_scouter
    ) 
    REFERENCES SAL_PERSONAL 
    ( 
     ID_personal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SAL_TESORERO 
    ADD CONSTRAINT SAL_TESORERO_SAL_PERSONAL_FK FOREIGN KEY 
    ( 
     ID_tesorero
    ) 
    REFERENCES SAL_PERSONAL 
    ( 
     ID_personal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

