USE SAL_SCOUTS
GO

ALTER TABLE SAL_PERSONAL
	ADD scout_user VARCHAR(50);
GO

UPDATE SAL_PERSONAL SET scout_user = 'JRM_SCOUTS' WHERE ID_personal = 1;
UPDATE SAL_PERSONAL SET scout_user = 'SAL_SCOUTS' WHERE ID_personal = 2;
UPDATE SAL_PERSONAL SET scout_user = 'LGM_SCOUTS' WHERE ID_personal = 3;
UPDATE SAL_PERSONAL SET scout_user = 'SDDT_SCOUTS' WHERE ID_personal = 4;
UPDATE SAL_PERSONAL SET scout_user = 'ACM_SCOUTS' WHERE ID_personal = 5;
UPDATE SAL_PERSONAL SET scout_user = 'AMP_SCOUTS' WHERE ID_personal = 6;
UPDATE SAL_PERSONAL SET scout_user = 'MMO_SCOUTS' WHERE ID_personal = 7;
UPDATE SAL_PERSONAL SET scout_user = 'DGC_SCOUTS' WHERE ID_personal = 8;
UPDATE SAL_PERSONAL SET scout_user = 'SHAL_SCOUTS' WHERE ID_personal = 9;
GO
-- (9 rows affected)
			
SELECT ID_personal,scout_user FROM SAL_PERSONAL
GO

-- ID_personal	scout_user
-- 1			JRM_SCOUTS
-- 2			SAL_SCOUTS
-- 3			LGM_SCOUTS
-- 4			SDDT_SCOUTS
-- 5			ACM_SCOUTS
-- 6			AMP_SCOUTS
-- 7			MMO_SCOUTS
-- 8			DGC_SCOUTS
-- 9			SHAL_SCOUTS

SELECT d.*, p.scout_user AS scout_user
	FROM SAL_DONACION d
		JOIN SAL_TESORERO ON d.SAL_TESORERO_ID_personal = SAL_TESORERO.ID_tesorero 
		JOIN SAL_PERSONAL p ON SAL_TESORERO.ID_tesorero = p.ID_personal;
GO

REVOKE SELECT,INSERT,UPDATE,DELETE ON SAL_DONACION TO Tesorero;
GRANT SELECT,INSERT,UPDATE,DELETE ON TREASURER.DONATION TO Tesorero;
--GRANT IMPERSONATE ON USER::[NoMask] TO [MMO_SCOUTS];
--GRANT IMPERSONATE ON USER::[NoMask] TO [DGC_SCOUTS];
--GRANT IMPERSONATE ON USER::[NoMask] TO [SHAL_SCOUTS];
GRANT UNMASK TO Tesorero; -- Para que los valores no se encuentren enmascarados
GO

DROP SCHEMA IF EXISTS TREASURER
GO

CREATE SCHEMA TREASURER
GO

DROP VIEW IF EXISTS TREASURER.DONATION
GO

CREATE VIEW TREASURER.DONATION WITH SCHEMABINDING
AS
	SELECT d.ID_donacion,d.fecha_donacion,d.nombre_donante,d.importe,d.SAL_EVENTOS_ID_evento,d.SAL_TESORERO_ID_personal, p.scout_user AS scout_user
	FROM dbo.SAL_DONACION d
		JOIN dbo.SAL_TESORERO ON d.SAL_TESORERO_ID_personal = SAL_TESORERO.ID_tesorero 
		JOIN dbo.SAL_PERSONAL p ON SAL_TESORERO.ID_tesorero = p.ID_personal;
GO
-- CON 'WITH SCHEMABINDING'

SELECT * FROM TREASURER.DONATION
GO

-- Controlamos la existencia de la función
DROP FUNCTION IF EXISTS TREASURER.SALfnDON
GO

CREATE OR ALTER FUNCTION TREASURER.SALfnDON (@scout_user SYSNAME) 
    RETURNS TABLE
	WITH SCHEMABINDING
AS 
    RETURN SELECT 1 AS treasurer_filter
            WHERE @scout_user = USER_NAME() 
               OR (USER_NAME() IN ('dbo','dbo')); -- EN PRINCIPIO DEBERÍA SER 'ACM_SCOUTS', no otra vez 'dbo' | ¿ES UN BUG?
			   -- SIN ESTE APARTADO, dbo no PODRÍA VISUALIZAR NINGÚN CAMPO DE LA VISTA TREASURER.DONATION
GO

-- Controlamos la existencia de la directiva de seguridad
DROP SECURITY POLICY IF EXISTS TREASURER.SAL_SPOscouts_don
GO

CREATE SECURITY POLICY TREASURER.SAL_SPOscouts_don  
	ADD FILTER PREDICATE TREASURER.SALfnDON(scout_user)   
	ON TREASURER.DONATION
		WITH (STATE = ON);
GO

SELECT * FROM TREASURER.DONATION
GO

-- Comprobación
EXECUTE AS USER = 'ACM_SCOUTS';
PRINT USER_NAME();
SELECT * FROM TREASURER.DONATION;
REVERT;
GO

EXECUTE AS USER = 'DGC_SCOUTS';
PRINT USER_NAME();
SELECT * FROM TREASURER.DONATION;
REVERT;
GO

EXECUTE AS USER = 'MMO_SCOUTS';
PRINT USER_NAME();
SELECT * FROM TREASURER.DONATION;
REVERT;
GO

EXECUTE AS USER = 'SHAL_SCOUTS';
PRINT USER_NAME();
SELECT * FROM TREASURER.DONATION;
REVERT;
GO